### ISSUE TITLE
Checklist for Workshop 2

### ISSUE THREAD

**Issue by DamienBAus** [DamienBAus/FranklyTinyMessenger#16]
- [x] E-mail out slides
- [x] E-mail out base files
- [x] Have expedia/free fonts tab open
- [x] Have a working copy of the files, up until the end of workshop two on my computer
